#!/usr/bin/env bash
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; PROJECT="$PWD"; MODE=both; DRY=0; FORCE=0; AGENTS=all
while (($#)); do case "$1" in --project-only) MODE=project;; --global-only) MODE=global;; --dry-run) DRY=1;; --force) FORCE=1;; --project) shift; PROJECT="$1";; --agents) shift; AGENTS="$1";; -h|--help) echo 'install.sh [--project-only|--global-only] [--dry-run] [--force] [--project PATH] [--agents all,codex,claude,cursor,copilot,gemini,antigravity,generic]'; exit 0;; *) echo "Unknown option: $1" >&2; exit 2;; esac; shift; done
CORE="$(cat "$ROOT/core/enterprise-audit.md")"; AGENT="$(cat "$ROOT/AGENTS.md")"; FAILED=0; CHANGED=0; SKIPPED=0
has(){ [[ ",$AGENTS," == *,all,* || ",$AGENTS," == *,$1,* ]]; }
write_safe(){ local path="$1" content="$2" append="${3:-0}"; mkdir_cmd=(mkdir -p "$(dirname "$path")"); if [[ -f "$path" ]]; then if [[ "$append" == 1 ]] && grep -q 'Universal Enterprise Audit Agent Instructions' "$path"; then ((SKIPPED++)); return; fi; if [[ "$append" != 1 && "$FORCE" != 1 ]]; then echo "[SKIP] exists: $path (use --force)"; ((SKIPPED++)); return; fi; fi; echo "$([[ $DRY == 1 ]] && echo '[DRY]' || echo '[WRITE]') $path"; [[ $DRY == 1 ]] && { ((CHANGED++)); return; }; "${mkdir_cmd[@]}" || { ((FAILED++)); return; }; if [[ -f "$path" ]]; then cp "$path" "$path.ai-audit.bak" || { ((FAILED++)); return; }; fi; if [[ "$append" == 1 && -f "$path" ]]; then printf '\n\n%s\n' "$content" >> "$path" || ((FAILED++)); else printf '%s\n' "$content" > "$path" || ((FAILED++)); fi; ((CHANGED++)); }
project_install(){ local p="$1"; (has generic || has codex) && write_safe "$p/AGENTS.md" "$AGENT" 1; has claude && write_safe "$p/CLAUDE.md" "$AGENT" 1; has gemini && write_safe "$p/GEMINI.md" "$AGENT" 1; has cursor && write_safe "$p/.cursor/rules/enterprise-audit.mdc" $'---\ndescription: Universal evidence-based enterprise code audit protocol\nalwaysApply: false\n---\n\n'"$CORE"; has copilot && write_safe "$p/.github/instructions/enterprise-audit.instructions.md" $'---\napplyTo: "**/*"\n---\n\n'"$CORE"; has antigravity && write_safe "$p/.antigravity/skills/enterprise-audit/SKILL.md" "$CORE"; write_safe "$p/.ai-audit/core/enterprise-audit.md" "$CORE"; }
[[ "$MODE" != global ]] && project_install "$PROJECT"
if [[ "$MODE" != project ]]; then has codex && write_safe "$HOME/.codex/skills/enterprise-audit/SKILL.md" "$CORE"; has claude && write_safe "$HOME/.claude/CLAUDE.md" "$AGENT" 1; has cursor && write_safe "$HOME/.cursor/rules/enterprise-audit.mdc" $'---\ndescription: Universal enterprise audit\nalwaysApply: false\n---\n\n'"$CORE"; has copilot && write_safe "$HOME/.copilot/instructions/enterprise-audit.instructions.md" $'---\napplyTo: "**/*"\n---\n\n'"$CORE"; has antigravity && write_safe "$HOME/.antigravity/skills/enterprise-audit/SKILL.md" "$CORE"; fi
echo "Changed=$CHANGED Skipped=$SKIPPED Failed=$FAILED"; (( FAILED == 0 ))
